name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Inject SEO Content
        run: |
          cp -f seo/index.html dist/index.html
          cp -f seo/robots.txt dist/robots.txt
          cp -f seo/sitemap.xml dist/sitemap.xml

      - name: Upload Build to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist"
          target: ${{ secrets.TARGET_PATH }}

      - name: Finalize Deployment & Restart Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            rsync -a --delete /var/www/portfolio/ /var/www/portfolio_backup/
            rsync -a --delete /var/www/temp_build/dist/ /var/www/portfolio/
            sudo systemctl restart nginx
